"""Emit data/catalog.js for the app: deduped products w/ local images + facilities + series stats.

Keys kept short for size: id,n,code,cat,brand,series,sname,purp,mats,age,sp{d,f,u,z},img,url
"""
from io import BytesIO
from collections import Counter
import json, os, re, sys
from urllib.parse import unquote
import requests
from PIL import Image

sys.stdout.reconfigure(encoding="utf-8")
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
H = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/126.0 Safari/537.36"}

norm = json.load(open(os.path.join(BASE, "crawl", "catalog.norm.json"), encoding="utf-8"))
imgmap = json.load(open(os.path.join(BASE, "crawl", "images.map.json"), encoding="utf-8"))

seen, products = set(), []
dupes = 0
for p in norm:
    pid = unquote(p["id"])  # files on disk use decoded names (server decodes URLs)
    if pid in seen:
        dupes += 1
        continue
    seen.add(pid)
    imgs = [unquote(f) for f in imgmap.get(p["id"], imgmap.get(pid, [])) ]
    imgs = [f for f in imgs if os.path.exists(os.path.join(BASE, f))]
    if not imgs:
        continue  # no visual = no grid card
    sp = {k: v for k, v in (("d", p["specs"]["dims"]), ("f", p["specs"]["fall"]),
                            ("u", p["specs"]["users"]), ("z", p["specs"]["zone"])) if v}
    products.append({
        "id": pid, "n": p["n"], "code": p["code"], "cat": p["cat"], "brand": p["brand"],
        "series": p["series"], "sname": p["sname"], "purp": p["purp"][0], "mats": p["mats"],
        "age": p["age"], "sp": sp, "img": imgs,
    })
print("dedup dupes:", dupes, "final with images:", len(products))

# ---- facilities: download thumbs (first 24 with image) ----
fac = json.load(open(os.path.join(BASE, "crawl", "facilities.json"), encoding="utf-8"))
os.makedirs(os.path.join(BASE, "img", "fac"), exist_ok=True)
fout = []
for f in fac:
    if f["slug"] == "facilities":
        continue
    fslug = unquote(f["slug"])  # web server decodes URLs -> filename must be decoded
    srcs = (f.get("imgs") or ([f["img"]] if f.get("img") else []))[:4]
    kept = []
    for i, src in enumerate(srcs):
        if not src:
            continue
        fn = f"img/fac/{fslug}_{i+1}.webp"
        ap = os.path.join(BASE, fn)
        if not (os.path.exists(ap) and os.path.getsize(ap) > 1000):
            try:
                r = requests.get(src, headers=H, timeout=30)
                if r.status_code != 200 or len(r.content) < 1000:
                    continue
                im = Image.open(BytesIO(r.content)).convert("RGB")
                im.thumbnail((1100, 1100), Image.LANCZOS)
                im.save(ap, "WEBP", quality=78, method=4)
            except Exception:
                continue
        kept.append(fn)
    if not kept:
        continue
    fout.append({"t": f["title"], "loc": f.get("loc", "").strip(), "img": kept[0], "imgs": kept, "url": f.get("url", "")})
print("facilities kept:", len(fout))

# ---- target groups (audiences) ----
os.makedirs(os.path.join(BASE, "img", "tgt"), exist_ok=True)
tout = []
targets = json.load(open(os.path.join(BASE, "crawl", "targets.json"), encoding="utf-8")) if os.path.exists(os.path.join(BASE, "crawl", "targets.json")) else []
for tg in targets:
    kept = []
    for i, src in enumerate(tg.get("imgs", [])[:4]):
        fn = f"img/tgt/{tg['slug']}_{i+1}.webp"
        ap = os.path.join(BASE, fn)
        if not (os.path.exists(ap) and os.path.getsize(ap) > 1000):
            try:
                r = requests.get(src, headers=H, timeout=30)
                if r.status_code != 200 or len(r.content) < 1000:
                    continue
                im = Image.open(BytesIO(r.content)).convert("RGB")
                im.thumbnail((1100, 1100), Image.LANCZOS)
                im.save(ap, "WEBP", quality=78, method=4)
            except Exception:
                continue
        kept.append(fn)
    tout.append({"slug": tg["slug"], "title": tg["title"], "paras": tg.get("paras", [])[:2], "imgs": kept, "url": tg["url"]})
print("targets kept:", len(tout))

series_count = Counter(p["series"] for p in products if p["series"])

payload = {
    "generated": "2026-08-30",
    "count": len(products),
    "products": products,
    "facilities": fout,
    "targets": tout,
}
os.makedirs(os.path.join(BASE, "data"), exist_ok=True)
with open(os.path.join(BASE, "data", "catalog.js"), "w", encoding="utf-8") as f:
    f.write("// Generated by tools/build_data.py from infraconcept.bg crawl — do not hand-edit product rows.\n")
    f.write("window.IC_DATA=" + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";\n")
print("catalog.js bytes:", os.path.getsize(os.path.join(BASE, "data", "catalog.js")))
